version: '3.6'

services:
  report:
    image: docker.ub.gu.se/ub-reports:release-2022.11.002
    environment:
      KOHA_MY_DB_HOST: ${KOHA_MY_DB_HOST}
      KOHA_MY_DB_USER: ${KOHA_MY_DB_USER}
      KOHA_MY_DB_PASS: ${KOHA_MY_DB_PASS}
      KOHA_MY_DB_NAME: ${KOHA_MY_DB_NAME}
    network_mode: host
    volumes:
      - "$PWD/output:/apps/output"
